apiVersion: v1
kind: Service
metadata:
  name: example-cars-svc
spec:
  selector:
    app: example-cars
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-cars
  labels:
    app: example-cars
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-cars
  template:
    metadata:
      labels:
        app: example-cars
    spec:
      containers:
        - name: example-cars
          image: localhost:5000/example-cars
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
