version: "3.9"
services:
  api:
    image: example-cars:latest
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "80:8000"
    volumes:
      - ./app:/app

  mongo:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_db:/data/db
      - mongo_configdb:/data/configdb

volumes:
  mongo_db:
  mongo_configdb:
